theme: jekyll-theme-dinky
title: Tate Taylor
description: I am Tate Taylor, a Skyrim modder and Wabbajack modlist curator.
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
