theme: jekyll-theme-dinky
title: Tate Taylor
description: My name is Tate Taylor, Skyrim mod author and Wabbajack modlist curator.
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
