title: "Tate Taylor"
description: "I am Tate Taylor, a Skyrim mod author and Wabbajack modlist curator."
url: "https://tatetayloroh.com"
excerpt_separator: "<!-- excerpt-end -->"

collections:
  rickard-calvert:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      title: "About Me"
      image: "/assets/img/thumbnail.png"
  - scope:
      type: "posts"
    values:
      layout: "post"
      image_align: "center"
      permalink: "/posts/:title"
  - scope:
      type: "rickard-calvert"
    values:
        layout: "post"
        image_align: "center"
  - scope:
      path: "_rickard-calvert/ecss"
    values:
        series: "ecss"
        permalink: "/rickard-calvert/ecss/:title"
        
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 9 # Number of posts per page
paginate_path: "/page:num" # Path for pagination
