theme: jekyll-theme-dinky
title: Tate Taylor
description: I am Tate Taylor, a Skyrim mod author and Wabbajack modlist curator.
baseurl: /
excerpt_separator: "<!--more-->"
show_downloads: true
plugins:
  - jekyll-paginate
paginate: 5  # Number of posts per page
paginate_path: "/page:num"  # Path for pagination
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
utterances:
  repo: TateTaylorOH/TateTaylorOH
  theme: github-dark
