theme: jekyll-theme-dinky
title: Tate Taylor
description: I am Tate Taylor, a Skyrim mod author and Wabbajack modlist curator.
baseurl: /TateTaylorOH
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
utterances:
  repo: TateTaylorOH/TateTaylorOH
  theme: github-dark
